[package]
name = "realtime-ascii-art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camera_capture = "0.5.0"
image = "0.24.5"
rscam = "0.5.5"
termsize = "0.1.6"
v4l = "0.13.1"
